import * as fs from 'fs';
import * as path from 'path';
import { ParsedModule, TranslationKey, PlaceholderInfo } from './arb_parser';
import { ArbParser } from './arb_parser';

export interface GeneratorConfig {
    outputPath: string;
    className: string;
    defaultLocale: string;
    supportedLocales: string[];
    generateCombinedArb: boolean;
    useDeferredLoading: boolean;
    /**
     * Sink for non-fatal generation warnings (bad ICU syntax, etc.).
     * Routed through the extension's level-aware logger; defaults to a no-op
     * so the generator stays usable outside VS Code.
     */
    onWarning?: (message: string) => void;
}

/** One key/locale pair on its way into a generated message lookup table. */
interface MessageEntry {
    /** Fully qualified lookup name, e.g. `home_itemCount`. */
    key: string;
    /** The translation for this locale (falling back to the default locale). */
    value: string;
    /**
     * Canonical parameter names, derived once from the default locale so every
     * locale's closure declares the same positional signature.
     */
    params: string[];
    locale: string;
    translationKey: TranslationKey;
}

/**
 * Lints suppressed in generated output. `implementation_imports` covers the
 * required `package:intl/src/intl_helpers.dart`; `library_prefixes` covers
 * script-coded import aliases like `modular_messages_zh_Hans_CN`.
 */
const GENERATED_IGNORES =
    '// ignore_for_file: non_constant_identifier_names, unnecessary_string_interpolations,\n' +
    '// ignore_for_file: unnecessary_string_escapes, unnecessary_brace_in_string_interps,\n' +
    '// ignore_for_file: implementation_imports, library_prefixes, unused_import, prefer_single_quotes';

export class DartGenerator {
    constructor(private config: GeneratorConfig) {}

    async generate(modules: ParsedModule[]): Promise<void> {
        // Ensure output directory exists
        fs.mkdirSync(this.config.outputPath, { recursive: true });

        // Generate main ML class
        await this.generateMainClass(modules);

        // Generate module classes
        for (const module of modules) {
            await this.generateModuleClass(module);
        }

        // Generate delegate
        await this.generateDelegate(modules);

        // Generate messages files for each locale
        await this.generateMessagesFiles(modules);

        // Generate combined ARB files if enabled
        if (this.config.generateCombinedArb) {
            await this.generateCombinedArbFiles(modules);
        }

        // Generate barrel file
        await this.generateBarrelFile(modules);
    }

    private async generateMainClass(modules: ParsedModule[]): Promise<void> {
        // Relative imports, sorted, after the package: block — the analyzer's
        // directives_ordering lint flags any other arrangement.
        const relativeImports = [
            `import 'app_localization_delegate.dart';`,
            `import 'intl/modular_messages_all.dart';`,
            ...modules.map((m) => `import '${this.toSnakeCase(m.name)}_l10n.dart';`),
        ]
            .sort()
            .join('\n');

        const moduleGetters = modules
            .map((m) => {
                const className = this.toPascalCase(m.name) + 'L10n';
                const fieldName = this.toCamelCase(m.name);
                return `  ${className} get ${fieldName} => _${fieldName}!;
  static ${className}? _${fieldName};`;
            })
            .join('\n');

        const moduleLoaders = modules
            .map((m) => {
                const className = this.toPascalCase(m.name) + 'L10n';
                const fieldName = this.toCamelCase(m.name);
                return `    _${fieldName} = ${className}.load(localeName);`;
            })
            .join('\n');

        const content = `// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by Modular Flutter L10n Extension
${GENERATED_IGNORES}
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

${relativeImports}

/// Main Modular Localization class providing access to all module translations.
///
/// In widgets (registers dependency — auto-rebuilds on locale change):
/// \`\`\`dart
/// Text(${this.config.className}.of(context).auth.email)
/// Text(${this.config.className}.of(context).home.welcomeMessage)
/// \`\`\`
///
/// In non-widget code (services, cubits, etc.):
/// \`\`\`dart
/// final title = ${this.config.className}.current.auth.email;
/// \`\`\`
///
/// ## One active locale at a time
///
/// Module accessors resolve against static state set by the most recent
/// [load], and message lookup goes through \`Intl.defaultLocale\`, which is
/// global. That is the right model for an app that switches locale wholesale.
///
/// It does **not** support rendering two locales simultaneously — a
/// side-by-side comparison view, or an RTL preview pane inside an LTR app.
/// Nested \`Localizations\` scopes with different locales will all read the
/// locale that loaded last.
class ${this.config.className} {
  ${this.config.className}._();

  static ${this.config.className}? _current;

  static ${this.config.className} get current {
    assert(
      _current != null,
      'No instance of ${this.config.className} was loaded. '
      'Try to initialize the ${this.config.className} delegate before accessing ${this.config.className}.current.',
    );
    return _current!;
  }

${moduleGetters}

  static const AppLocalizationDelegate delegate = AppLocalizationDelegate();

  static Future<${this.config.className}> load(Locale locale) async {
    final name = (locale.countryCode?.isEmpty ?? false)
        ? locale.languageCode
        : locale.toString();
    final localeName = Intl.canonicalizedLocale(name);
    Intl.defaultLocale = localeName;

    // Register message lookup tables for the locale
    await initializeModularMessages(localeName);

    final instance = ${this.config.className}._();
    ${this.config.className}._current = instance;

    // Load all module translations
${moduleLoaders}

    return instance;
  }

  static ${this.config.className} of(BuildContext context) {
    final instance = ${this.config.className}.maybeOf(context);
    assert(
      instance != null,
      'No instance of ${this.config.className} present in the widget tree. '
      'Did you add ${this.config.className}.delegate in localizationsDelegates?',
    );
    return instance!;
  }

  static ${this.config.className}? maybeOf(BuildContext context) {
    return Localizations.of<${this.config.className}>(context, ${this.config.className});
  }

  /// List of all supported locales
  static const List<Locale> supportedLocales = [
${this.config.supportedLocales.map((l) => this.generateLocaleConstructor(l)).join(',\n')}
  ];
}
`;

        const filePath = path.join(
            this.config.outputPath,
            `${this.toSnakeCase(this.config.className)}.dart`
        );
        fs.writeFileSync(filePath, content, 'utf-8');
    }

    /**
     * Generate proper Locale constructor for complex locales.
     * Handles: en, en_US, zh_Hans, zh_Hans_CN
     */
    private generateLocaleConstructor(locale: string): string {
        const parts = locale.split('_');

        if (parts.length === 1) {
            return `    Locale('${parts[0]}')`;
        } else if (parts.length === 2) {
            const [lang, second] = parts;
            if (/^[A-Z][a-z]{3}$/.test(second)) {
                return `    Locale.fromSubtags(languageCode: '${lang}', scriptCode: '${second}')`;
            } else {
                return `    Locale('${lang}', '${second}')`;
            }
        } else if (parts.length === 3) {
            const [lang, script, region] = parts;
            return `    Locale.fromSubtags(languageCode: '${lang}', scriptCode: '${script}', countryCode: '${region}')`;
        }

        return `    Locale('${locale}')`;
    }

    private async generateModuleClass(module: ParsedModule): Promise<void> {
        const className = this.toPascalCase(module.name) + 'L10n';

        const methods = module.keys
            .map((key) => this.generateMethod(key, module.name))
            .join('\n\n');

        const content = `// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by Modular Flutter L10n Extension
// Module: ${module.name}
${GENERATED_IGNORES}
import 'package:intl/intl.dart';

/// Localization class for the ${module.name} module.
class ${className} {
  ${className}._();

  static ${className}? _instance;

  static ${className} load(String localeName) {
    _instance = ${className}._();
    return _instance!;
  }

  static ${className} get instance {
    assert(_instance != null, '${className} not loaded');
    return _instance!;
  }

${methods}
}
`;

        const filePath = path.join(
            this.config.outputPath,
            `${this.toSnakeCase(module.name)}_l10n.dart`
        );
        fs.writeFileSync(filePath, content, 'utf-8');
    }

    private generateMethod(key: TranslationKey, moduleName: string): string {
        const defaultTranslation = key.translations[this.config.defaultLocale] || '';

        // Get ordered placeholders (respects metadata order if specified)
        const placeholders = ArbParser.getOrderedPlaceholders(defaultTranslation, key.placeholders);

        const hasIcuSyntax = ArbParser.hasIcuSyntax(defaultTranslation);
        const icuType = ArbParser.getIcuType(defaultTranslation);

        const description = key.description || defaultTranslation;
        const escapedDescription = this.escapeForDartDoc(description);

        // Validate ICU syntax if present
        if (hasIcuSyntax) {
            const validation = ArbParser.validateIcuSyntax(defaultTranslation);
            if (!validation.valid) {
                this.config.onWarning?.(
                    `Invalid ICU syntax in ${moduleName}.${key.key}: ${validation.error}`
                );
            }
        }

        // 0. Handle compound messages (multiple ICU expressions in one string)
        if (ArbParser.isCompoundMessage(defaultTranslation)) {
            return this.generateCompoundMethod(
                key, moduleName, defaultTranslation, escapedDescription, placeholders
            );
        }

        // 1. Handle ICU Plural Syntax
        if (icuType === 'plural' || icuType === 'selectordinal') {
            return this.generatePluralMethod(key, moduleName, defaultTranslation, escapedDescription, icuType);
        }

        // 2. Handle ICU Select Syntax
        if (icuType === 'select') {
            return this.generateSelectMethod(key, moduleName, defaultTranslation, escapedDescription);
        }

        // 3. Handle standard methods with parameters
        if (placeholders.length > 0) {
            return this.generateParameterizedMethod(key, moduleName, defaultTranslation, escapedDescription, placeholders);
        }

        // 4. Handle simple getters
        return `  /// ${escapedDescription}
  String get ${key.key} {
    return Intl.message(
      ${this.toDartLiteral(defaultTranslation, new Set())},
      name: '${moduleName}_${key.key}',
      desc: '${this.escapeDartString(key.description || '')}',
      args: [],
    );
  }`;
    }

    /**
     * Generate a method for plural/selectordinal ICU messages.
     */
    private generatePluralMethod(
        key: TranslationKey,
        moduleName: string,
        defaultTranslation: string,
        escapedDescription: string,
        icuType: 'plural' | 'selectordinal'
    ): string {
        const icuVarMatch = defaultTranslation.match(/\{(\w+)\s*,\s*(plural|selectordinal)\s*,/);
        const icuVar = icuVarMatch ? icuVarMatch[1] : 'count';

        const cases = this.extractPluralCases(defaultTranslation);

        return `  /// ${escapedDescription}
  String ${key.key}(int ${icuVar}) {
    return Intl.${icuType === 'selectordinal' ? 'plural' : 'plural'}(
      ${icuVar},
${this.generatePluralCaseLines(cases)}
      name: '${moduleName}_${key.key}',
      desc: '${this.escapeDartString(key.description || '')}',
      args: [${icuVar}],
    );
  }`;
    }

    /**
     * Generate a method for select ICU messages.
     */
    private generateSelectMethod(
        key: TranslationKey,
        moduleName: string,
        defaultTranslation: string,
        escapedDescription: string
    ): string {
        const icuVarMatch = defaultTranslation.match(/\{(\w+)\s*,\s*select\s*,/);
        const icuVar = icuVarMatch ? icuVarMatch[1] : 'choice';

        return `  /// ${escapedDescription}
  String ${key.key}(String ${icuVar}) {
    return Intl.select(
      ${icuVar},
      ${this.extractSelectCases(defaultTranslation)},
      name: '${moduleName}_${key.key}',
      desc: '${this.escapeDartString(key.description || '')}',
      args: [${icuVar}],
    );
  }`;
    }

    /**
     * Generate a method for compound messages (multiple ICU expressions in one string).
     * e.g., "{gender, select, male{He} other{They}} bought {count, plural, one{1 item} other{{count} items}}"
     *
     * Strategy: collect all ICU variables with their types, generate a method that
     * takes all of them as params, and build a Dart expression with embedded
     * Intl.plural/Intl.select calls.
     */
    private generateCompoundMethod(
        key: TranslationKey,
        moduleName: string,
        defaultTranslation: string,
        escapedDescription: string,
        orderedParams: string[]
    ): string {
        const segments = ArbParser.getIcuSegments(defaultTranslation);
        const icuTypes = new Map(segments.map((s) => [s.variable, s.type]));

        // ICU control variables are typed by their role (int for plural,
        // String for select); the rest fall back to placeholder metadata.
        const params = orderedParams
            .map((name) => {
                const icuType = icuTypes.get(name);
                if (icuType === 'plural' || icuType === 'selectordinal') return `int ${name}`;
                if (icuType === 'select') return `String ${name}`;
                return `${this.getPlaceholderDartType(key, name)} ${name}`;
            })
            .join(', ');

        const dartExpression = this.buildCompoundDartExpression(
            defaultTranslation,
            segments,
            new Set(orderedParams)
        );

        return `  /// ${escapedDescription}
  String ${key.key}(${params}) {
    return Intl.message(
      ${dartExpression},
      name: '${moduleName}_${key.key}',
      desc: '${this.escapeDartString(key.description || '')}',
      args: [${orderedParams.join(', ')}],
    );
  }`;
    }

    /**
     * Convert a compound ICU string into a Dart string literal with embedded
     * `Intl.plural` / `Intl.select` calls.
     *
     * Input:  `{gender, select, male{He} other{They}} bought {count, plural, one{1 item} other{{count} items}}`
     * Output: `'${Intl.select(gender, {'male': 'He', 'other': 'They'})} bought ${Intl.plural(count, one: '1 item', other: '$count items')}'`
     *
     * Assembled from alternating literal runs and generated expressions, so the
     * expressions are never fed through the escaper. Building the whole string
     * first and escaping it afterwards turns every `${…}` into inert text.
     */
    private buildCompoundDartExpression(
        text: string,
        segments: ReturnType<typeof ArbParser.getIcuSegments>,
        interpolate: Set<string>
    ): string {
        const sorted = [...segments].sort((a, b) => a.start - b.start);
        let body = '';
        let cursor = 0;

        for (const seg of sorted) {
            body += this.toDartLiteralBody(text.substring(cursor, seg.start), interpolate);

            if (seg.type === 'plural' || seg.type === 'selectordinal') {
                const caseArgs = this.buildInlinePluralArgs(this.extractPluralCases(seg.raw));
                body += `\${Intl.plural(${seg.variable}, ${caseArgs})}`;
            } else {
                body += `\${Intl.select(${seg.variable}, ${this.buildInlineSelectCases(seg.raw)})}`;
            }

            cursor = seg.end;
        }

        body += this.toDartLiteralBody(text.substring(cursor), interpolate);
        return `'${body}'`;
    }

    /**
     * Single-line `zero: 'none', one: '1 item', other: '$count items'` for an
     * Intl.plural call embedded in a larger expression.
     */
    private buildInlinePluralArgs(cases: Map<string, string>): string {
        return Array.from(this.resolvePluralCases(cases).entries())
            .map(([name, content]) => `${name}: ${this.toDartLiteral(content)}`)
            .join(', ');
    }

    /**
     * Generate a method with parameters.
     * Supports number/DateTime formatting from placeholder metadata.
     */
    private generateParameterizedMethod(
        key: TranslationKey,
        moduleName: string,
        defaultTranslation: string,
        escapedDescription: string,
        placeholders: string[]
    ): string {
        const params = placeholders
            .map((p) => `${this.getPlaceholderDartType(key, p)} ${p}`)
            .join(', ');

        // Placeholders carrying NumberFormat / DateFormat metadata are formatted
        // into a local first; the message then interpolates the formatted local.
        const formattingLines = this.generateFormattingLines(key, placeholders);
        const formattedFor = new Map(
            formattingLines.map((f) => [f.placeholder, f.formattedVar])
        );

        // The string handed to Intl.message is the runtime fallback — used
        // whenever the lookup misses (unsupported locale, or a call before
        // initializeModularMessages resolves). It has to be real Dart
        // interpolation, not the raw ARB text, or the user sees "Hello {name}".
        const messageSource = placeholders.reduce(
            (text, p) =>
                formattedFor.has(p)
                    ? text.split(`{${p}}`).join(`{${formattedFor.get(p)}}`)
                    : text,
            defaultTranslation
        );
        const interpolate = new Set(placeholders.map((p) => formattedFor.get(p) ?? p));
        const message = this.toDartLiteral(messageSource, interpolate);

        const args = placeholders.map((p) => formattedFor.get(p) ?? p);

        const formattedVars =
            formattingLines.length > 0
                ? formattingLines.map((f) => f.varDeclaration).join('\n    ') + '\n    '
                : '';

        return `  /// ${escapedDescription}
  String ${key.key}(${params}) {
    ${formattedVars}return Intl.message(
      ${message},
      name: '${moduleName}_${key.key}',
      desc: '${this.escapeDartString(key.description || '')}',
      args: [${args.join(', ')}],
    );
  }`;
    }

    /**
     * Generate formatting lines for placeholders with format metadata.
     * Supports NumberFormat and DateFormat.
     */
    private generateFormattingLines(
        key: TranslationKey,
        placeholders: string[]
    ): { placeholder: string; varDeclaration: string; formattedVar: string }[] {
        const lines: { placeholder: string; varDeclaration: string; formattedVar: string }[] = [];

        if (!key.placeholders) return lines;

        for (const pName of placeholders) {
            const meta = key.placeholders[pName];
            if (!meta || !meta.format) continue;

            const formattedVar = `${pName}String`;

            if (meta.type === 'DateTime') {
                if (meta.isCustomDateFormat === 'true') {
                    // Custom date format
                    lines.push({
                        placeholder: pName,
                        varDeclaration: `final ${formattedVar} = DateFormat('${this.escapeDartString(meta.format)}').format(${pName});`,
                        formattedVar,
                    });
                } else {
                    // Named date format (e.g., yMd, Hm)
                    lines.push({
                        placeholder: pName,
                        varDeclaration: `final ${formattedVar} = DateFormat.${meta.format}().format(${pName});`,
                        formattedVar,
                    });
                }
            } else if (meta.type === 'int' || meta.type === 'double' || meta.type === 'num') {
                // Number formatting
                const optParams = meta.optionalParameters;
                if (optParams) {
                    const paramEntries = Object.entries(optParams)
                        .map(([k, v]) => {
                            if (typeof v === 'number') return `${k}: ${v}`;
                            return `${k}: '${this.escapeDartString(String(v))}'`;
                        })
                        .join(', ');
                    lines.push({
                        placeholder: pName,
                        varDeclaration: `final ${formattedVar} = NumberFormat.${meta.format}(${paramEntries ? paramEntries : ''}).format(${pName});`,
                        formattedVar,
                    });
                } else {
                    lines.push({
                        placeholder: pName,
                        varDeclaration: `final ${formattedVar} = NumberFormat.${meta.format}().format(${pName});`,
                        formattedVar,
                    });
                }
            }
        }

        return lines;
    }

    /**
     * Extract plural cases from an ICU message.
     * Properly handles nested braces.
     */
    private extractPluralCases(icuString: string): Map<string, string> {
        const cases = new Map<string, string>();
        const caseNames = ['=0', '=1', '=2', 'zero', 'one', 'two', 'few', 'many', 'other'];

        for (const caseName of caseNames) {
            const content = this.extractCaseContent(icuString, caseName);
            if (content !== null) {
                cases.set(caseName, content);
            }
        }

        return cases;
    }

    /**
     * Extract the content of a specific case from an ICU message.
     * Properly handles nested braces.
     */
    private extractCaseContent(icuString: string, caseName: string): string | null {
        // Match the case with possible whitespace before the opening brace
        const searchPatterns = [
            `${caseName}{`,
            `${caseName} {`,
        ];

        let startIndex = -1;
        let searchLen = 0;

        for (const pattern of searchPatterns) {
            const idx = icuString.indexOf(pattern);
            if (idx !== -1 && (startIndex === -1 || idx < startIndex)) {
                startIndex = idx;
                searchLen = pattern.length;
            }
        }

        if (startIndex === -1) {
            return null;
        }

        const contentStart = startIndex + searchLen;
        let bracketCount = 1;
        let contentEnd = contentStart;

        for (let i = contentStart; i < icuString.length; i++) {
            if (icuString[i] === '{') {
                bracketCount++;
            } else if (icuString[i] === '}') {
                bracketCount--;
                if (bracketCount === 0) {
                    contentEnd = i;
                    break;
                }
            }
        }

        // Raw ICU text. Escaping and placeholder conversion happen at emit time
        // via toDartLiteralBody, so the two transforms can't fight each other.
        return icuString.substring(contentStart, contentEnd);
    }

    /**
     * Resolve ICU plural cases onto Dart's `Intl.plural` named parameters.
     *
     * `=0`/`=1`/`=2` map to `zero`/`one`/`two`, which `Intl.pluralLogic` checks
     * by exact value before consulting CLDR rules — so the explicit ICU
     * semantics survive. A named case wins over the explicit form when both
     * are present.
     */
    private resolvePluralCases(cases: Map<string, string>): Map<string, string> {
        const explicitToDartParam: Record<string, string> = {
            '=0': 'zero',
            '=1': 'one',
            '=2': 'two',
        };
        const namedCases = ['zero', 'one', 'two', 'few', 'many', 'other'];
        const resolved = new Map<string, string>();

        for (const [caseName, content] of cases.entries()) {
            if (caseName.startsWith('=')) {
                const dartParam = explicitToDartParam[caseName];
                if (dartParam && content.trim() && !resolved.has(dartParam)) {
                    resolved.set(dartParam, content);
                }
            }
        }

        for (const caseName of namedCases) {
            const content = cases.get(caseName);
            if (content !== undefined && content.trim()) {
                resolved.set(caseName, content);
            }
        }

        // Re-key in Intl.plural declaration order.
        const ordered = new Map<string, string>();
        for (const caseName of namedCases) {
            if (resolved.has(caseName)) {
                ordered.set(caseName, resolved.get(caseName)!);
            }
        }
        return ordered;
    }

    /** Multi-line `zero: '…',` argument list for a standalone Intl.plural call. */
    private generatePluralCaseLines(cases: Map<string, string>): string {
        return Array.from(this.resolvePluralCases(cases).entries())
            .map(([name, content]) => `      ${name}: ${this.toDartLiteral(content)},`)
            .join('\n');
    }

    /**
     * Parse `{var, select, a{…} b{…}}` into its case map, preserving the raw
     * (unescaped) ICU content. Handles nested braces in case bodies.
     */
    private parseSelectCases(icuString: string): Map<string, string> {
        const cases = new Map<string, string>();

        // Find the start of the select body (after "{var, select,")
        const selectStart = icuString.match(/\{\w+\s*,\s*select\s*,/);
        if (!selectStart) {
            return cases;
        }

        const bodyStart = (selectStart.index ?? 0) + selectStart[0].length;
        let pos = bodyStart;

        // Parse each case: caseName{content}
        while (pos < icuString.length) {
            // Skip whitespace
            while (pos < icuString.length && /\s/.test(icuString[pos])) {
                pos++;
            }

            // Check if we hit the closing brace of the select
            if (icuString[pos] === '}') {
                break;
            }

            // Read case name
            const caseNameMatch = icuString.substring(pos).match(/^(\w+)\s*\{/);
            if (!caseNameMatch) {
                break;
            }

            const caseName = caseNameMatch[1];
            pos += caseNameMatch[0].length;

            // Read content with balanced braces
            let braceDepth = 1;
            let contentStart = pos;

            while (pos < icuString.length && braceDepth > 0) {
                if (icuString[pos] === '{') braceDepth++;
                else if (icuString[pos] === '}') braceDepth--;
                if (braceDepth > 0) pos++;
            }

            cases.set(caseName, icuString.substring(contentStart, pos));
            pos++; // skip closing brace
        }

        return cases;
    }

    /** Multi-line Dart map literal for a standalone Intl.select call. */
    private extractSelectCases(icuString: string): string {
        const entries = Array.from(this.parseSelectCases(icuString).entries()).map(
            ([name, content]) => `'${name}': ${this.toDartLiteral(content)}`
        );
        if (entries.length === 0) {
            return '{}';
        }
        return `{\n        ${entries.join(',\n        ')},\n      }`;
    }

    /** Single-line Dart map literal for an embedded Intl.select call. */
    private buildInlineSelectCases(icuString: string): string {
        const entries = Array.from(this.parseSelectCases(icuString).entries()).map(
            ([name, content]) => `'${name}': ${this.toDartLiteral(content)}`
        );
        return `{${entries.join(', ')}}`;
    }

    /**
     * Get the Dart type for a placeholder, including proper DateTime support.
     */
    private getPlaceholderDartType(key: TranslationKey, placeholderName: string): string {
        if (key.placeholders && key.placeholders[placeholderName]) {
            const type = key.placeholders[placeholderName].type;
            switch (type) {
                case 'int':
                    return 'int';
                case 'num':
                    return 'num';
                case 'double':
                    return 'double';
                case 'DateTime':
                    return 'DateTime';
                case 'String':
                    return 'String';
                default:
                    return 'Object';
            }
        }
        return 'Object';
    }

    private async generateDelegate(modules: ParsedModule[]): Promise<void> {
        const content = `// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by Modular Flutter L10n Extension
${GENERATED_IGNORES}
import 'package:flutter/material.dart';
import '${this.toSnakeCase(this.config.className)}.dart';

class AppLocalizationDelegate extends LocalizationsDelegate<${this.config.className}> {
  const AppLocalizationDelegate();

  @override
  bool isSupported(Locale locale) => _resolve(locale) != null;

  @override
  Future<${this.config.className}> load(Locale locale) =>
      ${this.config.className}.load(_resolve(locale) ?? locale);

  /// Narrow [locale] to the closest supported locale.
  ///
  /// Matching a device locale on language alone (so \`en_GB\` satisfies a project
  /// that only ships \`en_US\`) is right, but the *device* locale must not then be
  /// handed to load() — no message table is registered under it. Resolve to the
  /// supported locale first: exact match, then language+country, then language.
  static Locale? _resolve(Locale locale) {
    for (final supported in ${this.config.className}.supportedLocales) {
      if (supported == locale) return supported;
    }
    for (final supported in ${this.config.className}.supportedLocales) {
      if (supported.languageCode == locale.languageCode &&
          supported.countryCode == locale.countryCode) {
        return supported;
      }
    }
    for (final supported in ${this.config.className}.supportedLocales) {
      if (supported.languageCode == locale.languageCode) return supported;
    }
    return null;
  }

  @override
  bool shouldReload(AppLocalizationDelegate old) => false;
}
`;

        const filePath = path.join(this.config.outputPath, 'app_localization_delegate.dart');
        fs.writeFileSync(filePath, content, 'utf-8');
    }

    private async generateMessagesFiles(modules: ParsedModule[]): Promise<void> {
        const messagesDir = path.join(this.config.outputPath, 'intl');
        fs.mkdirSync(messagesDir, { recursive: true });

        for (const locale of this.config.supportedLocales) {
            const messages: MessageEntry[] = [];
            for (const module of modules) {
                for (const key of module.keys) {
                    const translation =
                        key.translations[locale] ||
                        key.translations[this.config.defaultLocale] ||
                        '';

                    // The parameter list is derived once, from the default
                    // locale, and reused for every locale. intl dispatches
                    // through Function.apply, which binds positionally — so if
                    // each locale declared its own order, a translation that
                    // reorders placeholders (often required by grammar) would
                    // silently receive the arguments swapped.
                    const canonical = key.translations[this.config.defaultLocale] ?? '';
                    const params = ArbParser.getOrderedPlaceholders(canonical, key.placeholders);

                    messages.push({
                        key: `${module.name}_${key.key}`,
                        value: translation,
                        params,
                        locale,
                        translationKey: key,
                    });
                }
            }

            const content = this.generateMessagesFileContent(locale, messages);
            // FIXED: Namespaced file to avoid Flutter Intl conflict
            const filePath = path.join(messagesDir, `modular_messages_${locale}.dart`);
            fs.writeFileSync(filePath, content, 'utf-8');
        }

        // Generate modular_messages_all.dart
        await this.generateMessagesAll(modules);
    }

    /**
     * Generate the per-locale message lookup table.
     *
     * Entries in this map are the *resolution* of a message, so none of them may
     * pass `name:` / `args:` to `Intl.plural` / `Intl.select`. Supplying `name`
     * is what makes intl perform a lookup, and the lookup for that name resolves
     * back to this same closure — an unbounded recursion that ends in
     * StackOverflowError on the first call. Without `name`, `Intl.plural`
     * simply selects a branch and returns.
     */
    private generateMessagesFileContent(locale: string, messages: MessageEntry[]): string {
        let usesIntl = false;

        const messageEntries = messages
            .map((entry) => {
                const { key, value, params } = entry;
                const icuType = ArbParser.getIcuType(value);

                // 0. Compound messages (multiple top-level ICU expressions)
                if (ArbParser.isCompoundMessage(value)) {
                    usesIntl = true;
                    return this.generateMessageCompoundEntry(entry);
                }

                // 1. ICU plural / selectordinal
                if (icuType === 'plural' || icuType === 'selectordinal') {
                    usesIntl = true;
                    const icuVarMatch = value.match(/\{(\w+)\s*,\s*(plural|selectordinal)\s*,/);
                    const icuVar = icuVarMatch ? icuVarMatch[1] : 'count';
                    return this.generateMessagePluralEntry(key, icuVar, this.extractPluralCases(value));
                }

                // 2. ICU select
                if (icuType === 'select') {
                    usesIntl = true;
                    const icuVarMatch = value.match(/\{(\w+)\s*,\s*select\s*,/);
                    const icuVar = icuVarMatch ? icuVarMatch[1] : 'choice';
                    return this.generateMessageSelectEntry(key, icuVar, value);
                }

                // 3. Parameterized messages
                if (params.length > 0) {
                    this.warnAboutUnknownPlaceholders(entry);
                    const body = this.toDartLiteral(value, new Set(params));
                    return `    '${key}': (${params.join(', ')}) => ${body},`;
                }

                // 4. Simple static messages
                return `    '${key}': MessageLookupByLibrary.simpleMessage(${this.toDartLiteral(value, new Set())}),`;
            })
            .join('\n');

        // Only import intl when an entry actually calls into it, so projects
        // without ICU messages don't get an unused_import warning.
        const intlImport = usesIntl ? "import 'package:intl/intl.dart';\n" : '';

        return `// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by Modular Flutter L10n Extension
${GENERATED_IGNORES}
${intlImport}import 'package:intl/message_lookup_by_library.dart';

final messages = ModularMessageLookup();

class ModularMessageLookup extends MessageLookupByLibrary {
  @override
  String get localeName => '${locale}';

  @override
  final messages = <String, Function>{
${messageEntries}
  };
}
`;
    }

    /**
     * Warn when a translation uses a placeholder the default locale doesn't
     * declare. Such a placeholder can't become a parameter — the caller passes
     * arguments in the default locale's shape — so it is left as literal text
     * and the translator is told rather than shipping `{foo}` to users.
     */
    private warnAboutUnknownPlaceholders(entry: MessageEntry): void {
        if (entry.locale === this.config.defaultLocale) return;

        const declared = new Set(entry.params);
        for (const name of ArbParser.extractPlaceholders(entry.value)) {
            if (!declared.has(name)) {
                this.config.onWarning?.(
                    `[${entry.locale}] ${entry.key}: placeholder "{${name}}" is not in the ` +
                    `${this.config.defaultLocale} translation and will render literally. ` +
                    `Available: ${entry.params.map((p) => `{${p}}`).join(', ') || '(none)'}`
                );
            }
        }
    }

    /**
     * Compound message entry: a closure with embedded Intl.plural/Intl.select
     * calls, taking the key's canonical parameter list.
     */
    private generateMessageCompoundEntry(entry: MessageEntry): string {
        this.warnAboutUnknownPlaceholders(entry);

        const segments = ArbParser.getIcuSegments(entry.value);
        const expression = this.buildCompoundDartExpression(
            entry.value,
            segments,
            new Set(entry.params)
        );

        return `    '${entry.key}': (${entry.params.join(', ')}) => ${expression},`;
    }

    /** Plural entry. No `name:`/`args:` — see generateMessagesFileContent. */
    private generateMessagePluralEntry(
        key: string,
        icuVar: string,
        cases: Map<string, string>
    ): string {
        return `    '${key}': (${icuVar}) => Intl.plural(${icuVar}, ${this.buildInlinePluralArgs(cases)}),`;
    }

    /** Select entry. No `name:`/`args:` — see generateMessagesFileContent. */
    private generateMessageSelectEntry(
        key: string,
        icuVar: string,
        value: string
    ): string {
        return `    '${key}': (${icuVar}) => Intl.select(${icuVar}, ${this.buildInlineSelectCases(value)}),`;
    }

    private async generateMessagesAll(modules: ParsedModule[]): Promise<void> {
        // FIXED: Namespaced imports and function to avoid Flutter Intl conflict
        const localeImports = this.config.supportedLocales
            .map((l) => `import 'modular_messages_${l}.dart' as modular_messages_${l.replace(/-/g, '_')};`)
            .join('\n');

        const deferredImports = this.config.useDeferredLoading
            ? this.config.supportedLocales
                .map((l) => `import 'modular_messages_${l}.dart' deferred as modular_messages_${l.replace(/-/g, '_')};`)
                .join('\n')
            : '';

        const actualImports = this.config.useDeferredLoading ? deferredImports : localeImports;

        const localeKey = (l: string) => l.replace(/-/g, '_');

        const deferredLibraries = this.config.useDeferredLoading
            ? this.config.supportedLocales
                .map((l) => `  '${l}': () => modular_messages_${localeKey(l)}.loadLibrary(),`)
                .join('\n')
            : this.config.supportedLocales
                .map((l) => `  '${l}': () => Future.value(null),`)
                .join('\n');

        const content = `// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by Modular Flutter L10n Extension
${GENERATED_IGNORES}
import 'package:intl/intl.dart';
import 'package:intl/message_lookup_by_library.dart';
import 'package:intl/src/intl_helpers.dart';

${actualImports}

typedef LibraryLoader = Future<dynamic> Function();

Map<String, LibraryLoader> _deferredLibraries = {
${deferredLibraries}
};

MessageLookupByLibrary? _findExact(String localeName) {
  switch (localeName) {
${this.config.supportedLocales.map((l) => `    case '${l}':\n      return modular_messages_${localeKey(l)}.messages;`).join('\n')}
    default:
      return null;
  }
}

MessageLookupByLibrary? _findGeneratedMessagesFor(String locale) {
  final actualLocale = Intl.verifiedLocale(
    locale,
    (locale) => _deferredLibraries[locale] != null,
    onFailure: (_) => null,
  );
  if (actualLocale == null) return null;
  return _findExact(actualLocale);
}

/// Initialize modular localization messages.
/// Named differently from Flutter Intl's initializeMessages to avoid conflicts.
Future<bool> initializeModularMessages(String localeName) async {
  final availableLocale = Intl.verifiedLocale(
    localeName,
    (locale) => _deferredLibraries[locale] != null,
    onFailure: (_) => null,
  );
  if (availableLocale == null) {
    return false;
  }
  final lib = _deferredLibraries[availableLocale];
  await lib?.call();
  initializeInternalMessageLookup(CompositeMessageLookup.new);
  messageLookup.addLocale(availableLocale, _findGeneratedMessagesFor);
  return true;
}
`;

        // FIXED: Namespaced filename to avoid conflicts
        const filePath = path.join(this.config.outputPath, 'intl', 'modular_messages_all.dart');
        fs.writeFileSync(filePath, content, 'utf-8');
    }

    private async generateCombinedArbFiles(modules: ParsedModule[]): Promise<void> {
        const arbDir = path.join(this.config.outputPath, 'arb');
        fs.mkdirSync(arbDir, { recursive: true });

        for (const locale of this.config.supportedLocales) {
            // Date only, no clock time: a full ISO timestamp changes on every
            // run, so watch mode would mark these files dirty on every save.
            const combinedArb: Record<string, unknown> = {
                '@@locale': locale,
                '@@last_modified': new Date().toISOString().split('T')[0],
            };

            for (const module of modules) {
                for (const key of module.keys) {
                    const fullKey = `${module.name}_${key.key}`;
                    combinedArb[fullKey] =
                        key.translations[locale] ||
                        key.translations[this.config.defaultLocale] ||
                        '';

                    if (key.description || key.placeholders) {
                        combinedArb[`@${fullKey}`] = {
                            description: key.description,
                            placeholders: key.placeholders,
                        };
                    }
                }
            }

            const filePath = path.join(arbDir, `modular_l10n_${locale}.arb`);
            this.writeIfChanged(filePath, JSON.stringify(combinedArb, null, 2));
        }
    }

    private async generateBarrelFile(modules: ParsedModule[]): Promise<void> {
        const exports = [
            `export '${this.toSnakeCase(this.config.className)}.dart';`,
            `export 'app_localization_delegate.dart';`,
            ...modules.map((m) => `export '${this.toSnakeCase(m.name)}_l10n.dart';`),
        ].sort();

        const content = `// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by Modular Flutter L10n Extension
${GENERATED_IGNORES}
${exports.join('\n')}
`;

        const filePath = path.join(this.config.outputPath, 'l10n.dart');
        fs.writeFileSync(filePath, content, 'utf-8');
    }

    /**
     * Write only when the content differs from what's on disk.
     *
     * Generated output is regenerated on every ARB save in watch mode; rewriting
     * byte-identical files churns mtimes, and for the combined ARBs it puts them
     * in every `git status` for no reason.
     */
    private writeIfChanged(filePath: string, content: string): void {
        try {
            if (fs.existsSync(filePath) && fs.readFileSync(filePath, 'utf-8') === content) {
                return;
            }
        } catch {
            // Unreadable: fall through and overwrite.
        }
        fs.writeFileSync(filePath, content, 'utf-8');
    }

    // ─── String utilities ────────────────────────────────────────────────

    private toPascalCase(str: string): string {
        return str
            .split(/[_-]/)
            .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
            .join('');
    }

    private toCamelCase(str: string): string {
        const pascal = this.toPascalCase(str);
        return pascal.charAt(0).toLowerCase() + pascal.slice(1);
    }

    private toSnakeCase(str: string): string {
        return str
            .replace(/([a-z])([A-Z])/g, '$1_$2')
            .replace(/[-\s]/g, '_')
            .toLowerCase();
    }

    /**
     * Escape a run of **literal** text for a single-quoted Dart string.
     *
     * `$` becomes `\$` here, which is correct for text that must render
     * verbatim — but it also means this must never be applied to interpolation
     * that the generator has synthesised. Use {@link toDartLiteralBody} to build
     * a literal that mixes both.
     */
    private escapeDartString(str: string): string {
        return str
            .replace(/\\/g, '\\\\')
            .replace(/'/g, "\\'")
            .replace(/\n/g, '\\n')
            .replace(/\r/g, '\\r')
            .replace(/\t/g, '\\t')
            .replace(/\$/g, '\\$');
    }

    /**
     * Build the body of a single-quoted Dart string from ARB text, turning
     * `{name}` placeholders into live interpolations and escaping everything
     * around them.
     *
     * The ordering matters and is the whole point of this helper: escaping a
     * string that already contains `$name` turns the interpolation into the
     * literal characters `\$name`, so the user sees `$name` on screen. Literal
     * runs are escaped individually and the interpolations are emitted raw.
     *
     * `{name}` is written as `$name` when the following character can't extend
     * the identifier, and `${name}` when it can — so `{n}items` yields
     * `${n}items`, not the undefined identifier `$nitems`.
     *
     * `interpolate` limits which names become interpolations; anything outside
     * it is left as literal `{name}` text. Locale files pass the canonical
     * parameter list here so a rogue placeholder in one translation can't
     * reference an undeclared variable and break the build.
     */
    private toDartLiteralBody(text: string, interpolate?: Set<string>): string {
        let out = '';
        let literalStart = 0;
        let i = 0;

        const flushLiteral = (end: number) => {
            if (end > literalStart) {
                out += this.escapeDartString(text.substring(literalStart, end));
            }
        };

        while (i < text.length) {
            if (text[i] !== '{') {
                i++;
                continue;
            }

            const match = text.substring(i).match(/^\{(\w+)\}/);
            if (!match || (interpolate && !interpolate.has(match[1]))) {
                i++;
                continue;
            }

            flushLiteral(i);

            const name = match[1];
            const after = text[i + match[0].length];
            const needsBraces = after !== undefined && /[A-Za-z0-9_]/.test(after);
            out += needsBraces ? `\${${name}}` : `$${name}`;

            i += match[0].length;
            literalStart = i;
        }

        flushLiteral(text.length);
        return out;
    }

    /** {@link toDartLiteralBody} wrapped in the surrounding quotes. */
    private toDartLiteral(text: string, interpolate?: Set<string>): string {
        return `'${this.toDartLiteralBody(text, interpolate)}'`;
    }

    /**
     * Escape string for Dart doc comments.
     */
    private escapeForDartDoc(str: string): string {
        return str
            .replace(/`/g, "'")
            .replace(/\n/g, ' ')
            .replace(/\r/g, ' ')
            .substring(0, 200);
    }
}